export const COUNTER_CHANGE = 'COUNTER_CHANGE'
export const CART_ADD = 'CART_ADD'
export const SAVE_PRODUCTS = 'SAVE_PRODUCTS'
export const SAVE_CATEGORIES = 'SAVE_CATEGORIES'
export const TOP_PRODUCTS = [4801, 1251, 3439]
export const TWILIO_URL = 'https://vodavspb.ru/api/sms/'
export const MAP_KEY_ANDROID = 'AIzaSyCvFajV9y_8kG2C9k45Sg38i5WTfjwqmZQ';
export const MAP_KEY_IOS = 'AIzaSyBZMoYh_5SZl81ILzxF4Tttc5NVk0y0xL4';
export const MAP_KEY_DEVELOP = 'AIzaSyB1t7W73Ersoz8TaCCoavj-bnPD7jXdAX0';