export const TOP_PRODUCTS = [4801, 1251, 3439]
export const TWILIO_URL = 'https://vodavspb.ru/api/sms/'
export const MAP_KEY_ANDROID = 'AIzaSyCvFajV9y_8kG2C9k45Sg38i5WTfjwqmZQ';
export const MAP_KEY_IOS = 'AIzaSyBZMoYh_5SZl81ILzxF4Tttc5NVk0y0xL4';
export const MAP_KEY_DEVELOP = 'AIzaSyB1t7W73Ersoz8TaCCoavj-bnPD7jXdAX0';
export const COUNTER_CHANGE = 'COUNTER_CHANGE'
export const ADDRESS_CHANGE = 'ADDRESS_CHANGE'
export const ADDRESS_ADD = 'ADDRESS_ADD'
export const ADDRESS_CHOOSE = 'ADDRESS_CHOOSE'
export const CART_ADD = 'CART_ADD'
export const SAVE_PRODUCTS = 'SAVE_PRODUCTS'
export const SAVE_CATEGORIES = 'SAVE_CATEGORIES'
export const SET_UP_HEADER = 'SET_UP_HEADER'
export const IM_ON_SCREEN = 'IM_ON_SCREEN'
export const BOTTOM_SHEET = 'BOTTOM_SHEET'

const CONSTANTS = {
	TOP_PRODUCTS : [4801, 1251, 3439],
	TWILIO_URL : 'https://vodavspb.ru/api/sms/',
	MAP_KEY_ANDROID : 'AIzaSyCvFajV9y_8kG2C9k45Sg38i5WTfjwqmZQ',
	MAP_KEY_IOS : 'AIzaSyBZMoYh_5SZl81ILzxF4Tttc5NVk0y0xL4',
	MAP_KEY_DEVELOP : 'AIzaSyB1t7W73Ersoz8TaCCoavj-bnPD7jXdAX0',
	COUNTER_CHANGE : 'COUNTER_CHANGE',
	ADDRESS_CHANGE : 'ADDRESS_CHANGE',
	ADDRESS_ADD : 'ADDRESS_ADD',
	ADDRESS_CHOOSE : 'ADDRESS_CHOOSE',
	CART_ADD : 'CART_ADD',
	SAVE_PRODUCTS : 'SAVE_PRODUCTS',
	SAVE_CATEGORIES : 'SAVE_CATEGORIES',
	SET_UP_HEADER : 'SET_UP_HEADER',
	IM_ON_SCREEN : 'IM_ON_SCREEN',
	BOTTOM_SHEET : 'BOTTOM_SHEET',
	BOTTOM_SHEET_TOGGLE: 'BOTTOM_SHEET_TOGGLE',
	SET_AUTH: 'SET_AUTH'
}
export default CONSTANTS